config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#home'
  get 'admin/close_form'

  get 'admin/generate_matches'

  get 'admin/results'

  post 'admin/match_pair' => 'admin#match_pair'
  put 'admin/undo_pair' => 'admin#undo_pair'
  get '/forms' => 'forms#index'

  resources :tutors
  resources :teachers
  resources :students
  get 'forms/teacher'

  post 'forms/teacher' => 'forms#teacher'

  post 'forms/tutor' => 'forms#tutor'

  post 'forms/teacher_submit' => 'forms#teacher_submit'
  post 'forms/tutor_submit' => 'forms#tutor_submit'
  post 'forms/student_submit' => 'forms#student_submit'

  get 'forms/parent_student'

  get 'forms/tutor'

  root 'welcome#index'

end

app/views/admin/close_form.html.erb
<h1>Admin#close_form</h1>
<button type="button" name="button">Close the Forms</button>

app/views/admin/email.html.erb
<h1>Find me in app/views/forms/tutor.html.erb</h1>

app/views/admin/generate_matches.html.erb
<h3>Step 1. Manual Matching</h3>
<table>
  <tr>
    <th>Tutor   </th>
    <th>Student</th>
  </tr>
  <tr>
    <td>A</td>
    <td>B</td>
  </tr>
  <tr>
    <td>C</td>
    <td>D</td>
  </tr>
  <tr>
    <td>E</td>
    <td>F</td>
  </tr>
</table>
<h3>Step 2. Run Algorithm </h3>
<button type="button" name="button">Run Algorithm!</button>

app/views/admin/home.html.erb
<%= link_to "Close Form", admin_close_form_path %><br>
<%= link_to "Generate Matches", admin_generate_matches_path %><br>
<%= link_to "See Results", admin_results_path %>

app/views/admin/results.html.erb
<h1>Admin#results</h1>
<table>
  <tr>
    <th>Tutor   </th>
    <th>Student</th>
  </tr>
  <tr>
    <td>A</td>
    <td>B</td>
  </tr>
  <tr>
    <td>C</td>
    <td>D</td>
  </tr>
  <tr>
    <td>E</td>
    <td>F</td>
  </tr>
</table>