config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#home'
  get 'admin/close_form'

  get 'admin/generate_matches'

  get 'admin/results'

  post 'admin/match_pair' => 'admin#match_pair'
  put 'admin/undo_pair' => 'admin#undo_pair'
  get '/forms' => 'forms#index'

  resources :tutors
  resources :teachers
  resources :students
  get 'forms/teacher'

  post 'forms/teacher' => 'forms#teacher'

  post 'forms/tutor' => 'forms#tutor'

  post 'forms/teacher_submit' => 'forms#teacher_submit'
  post 'forms/tutor_submit' => 'forms#tutor_submit'
  post 'forms/student_submit' => 'forms#student_submit'

  get 'forms/parent_student'

  get 'forms/tutor'

  root 'welcome#index'

end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.fetch(:tutor, {})
    end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tutors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutors.each do |tutor| %>
      <tr>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor', new_tutor_path %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form' %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>